name = "genia"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [
  { pattern = "cyantiknya.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.cyantiknya.my.id", custom_domain = true },
  { pattern = "bakrie.ac.id.cyantiknya.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.cyantiknya.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.cyantiknya.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.cyantiknya.my.id", custom_domain = true },
  { pattern = "support.zoom.us.cyantiknya.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.cyantiknya.my.id", custom_domain = true },

  { pattern = "zxblues.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.zxblues.biz.id", custom_domain = true },
  { pattern = "bakrie.ac.id.zxblues.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.zxblues.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.zxblues.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.zxblues.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.zxblues.biz.id", custom_domain = true },
  { pattern = "cache.netflix.com.zxblues.biz.id", custom_domain = true },
]


[[kv_namespaces]]
binding = "SKYNET"
id = "167d6a62fb07471883a281b0da54523f"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/ilhamrazer01/inconigto-vpn/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/ilhamrazer01/inconigto-vpn/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/ilhamrazer01/inconigto-vpn/refs/heads/master/web/link.html"
